#!/bin/bash

battery_level=`acpi -b | awk '{print $4}' | tr -d ','`
#battery_level=`acpi -b | grep -E -o '[0-9][0-9]?[0-9]?'`
battery_status=`acpi -b | grep -E -o 'Charging'`
bat=`echo $battery_level | grep -E -o '[0-9][0-9]?[0-9]?'`


if [[ $bat =~ '100' && $battery_status == 'Charging' ]]; then
  echo "<span color='#00FF00'>DISCONNECT NOW  $battery_level</span>"
elif [[ $bat =~ '100' ]]; then
  echo "<span color='#00FF00'> $battery_level</span>"
elif [[ $battery_level > 95 && $battery_status == 'Charging' ]]; then
  echo "<span color='#00FF00'>DISCONNECT NOW  $battery_level</span>"
elif [[ $battery_level > 95 ]]; then
  echo "<span color='#00FF00'> $battery_level</span>"
elif [[ $battery_level > 75 && $battery_status == 'Charging' ]]; then
  echo "<span color='#9CFF04'>CHARGING  $battery_level</span>"
elif [[ $battery_level > 75 ]]; then
  echo "<span color='#9CFF04'> $battery_level</span>"
elif [[ $battery_level > 50 && $battery_status == 'Charging' ]]; then
  echo "<span color='#ECFF04'>CHARGING  $battery_level</span>"
elif [[ $battery_level > 50 ]]; then
  echo "<span color='#ECFF04'> $battery_level</span>"
elif [[ $battery_level > 25 && $battery_status == 'Charging' ]]; then
  echo "<span color='#FF4504'>CHARGING  $battery_level</span>"
elif [[ $battery_level > 25 ]]; then
  echo "<span color='#FF4504'> $battery_level</span>"
elif [[ $battery_level > 0 && $battery_status == 'Charging' ]]; then
  echo "<span color='#FF0404'>CHARGING  $battery_level</span>"
else
  echo "<span color='#FF0404'>CHARGE NOW  $battery_level</span>"
fi
